/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: OneSteven (https://sketchfab.com/Steven007)
license: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
source: https://sketchfab.com/3d-models/ford-mustang-gt-350r-65d9f8c4cd67412289d7ff4b7c73347e
title: Ford Mustang GT-350R
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={[0.01, 0.01, 0.01]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group position={[0, 41.23, 198.28]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object019_Material001_0.geometry} material={materials['Material.001']} />
            </group>
            <group position={[82.03, 16.93, -129.45]} rotation={[3.02, 0, 0]} scale={[0.99, 1.02, 1.02]}>
              <mesh geometry={nodes.cal003_Material006_0.geometry} material={nodes.cal003_Material006_0.material} />
            </group>
            <group position={[-82.03, 16.93, -129.45]} rotation={[3.02, 0, 0]} scale={[-0.99, 1.02, 1.02]}>
              <mesh geometry={nodes.cal002_Material006_0.geometry} material={nodes.cal002_Material006_0.material} />
            </group>
            <group position={[82.64, 16.94, -129.45]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.03, 0.04, 0.04]}>
              <mesh geometry={nodes.wheel002_sidewal_0.geometry} material={nodes.wheel002_sidewal_0.material} />
              <mesh geometry={nodes.wheel002_Material005_0.geometry} material={nodes.wheel002_Material005_0.material} />
              <mesh geometry={nodes.wheel002_tyre_0.geometry} material={nodes.wheel002_tyre_0.material} />
              <mesh geometry={nodes.wheel002_rim_0.geometry} material={nodes.wheel002_rim_0.material} />
            </group>
            <group position={[-82.64, 16.94, -129.45]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.03, 0.04, 0.04]}>
              <mesh geometry={nodes.wheel001_sidewal_0.geometry} material={nodes.wheel001_sidewal_0.material} />
              <mesh geometry={nodes.wheel001_Material005_0.geometry} material={nodes.wheel001_Material005_0.material} />
              <mesh geometry={nodes.wheel001_tyre_0.geometry} material={nodes.wheel001_tyre_0.material} />
              <mesh geometry={nodes.wheel001_rim_0.geometry} material={nodes.wheel001_rim_0.material} />
            </group>
            <group
              position={[-83.51, 17.73, 143.19]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 10]}
              scale={[0.04, 0.04, 0.04]}>
              <mesh geometry={nodes.wheel000_sidewal_0.geometry} material={nodes.wheel000_sidewal_0.material} />
              <mesh geometry={nodes.wheel000_Material005_0.geometry} material={nodes.wheel000_Material005_0.material} />
              <mesh geometry={nodes.wheel000_tyre_0.geometry} material={nodes.wheel000_tyre_0.material} />
              <mesh geometry={nodes.wheel000_rim_0.geometry} material={nodes.wheel000_rim_0.material} />
            </group>
            <group position={[83.51, 17.73, 143.38]} rotation={[-Math.PI / 2, 0, 2.83]} scale={[0.04, 0.04, 0.04]}>
              <mesh geometry={nodes.wheel003_sidewal_0.geometry} material={nodes.wheel003_sidewal_0.material} />
              <mesh geometry={nodes.wheel003_Material005_0.geometry} material={nodes.wheel003_Material005_0.material} />
              <mesh geometry={nodes.wheel003_tyre_0.geometry} material={nodes.wheel003_tyre_0.material} />
              <mesh geometry={nodes.wheel003_rim_0.geometry} material={nodes.wheel003_rim_0.material} />
            </group>
            <group position={[-82.93, 17.72, 143.38]} rotation={[0.03, -0.31, 0.01]} scale={[-1, 1, 1]}>
              <mesh geometry={nodes.cal001_Material006_0.geometry} material={nodes.cal001_Material006_0.material} />
            </group>
            <group position={[82.93, 17.72, 143.19]} rotation={[0.03, -0.31, 0.01]} scale={[1, 1, 1]}>
              <mesh geometry={nodes.cal_Material006_0.geometry} material={nodes.cal_Material006_0.material} />
            </group>
            <group position={[0, 97.06, -46.67]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object_Windows_0.geometry} material={materials.Windows} />
            </group>
            <group position={[0, 41.3, -1.78]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object010_grill_0.geometry} material={materials.grill} />
            </group>
            <group position={[0, 62.05, -2.18]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object001_Material015_0.geometry} material={materials['Material.015']} />
            </group>
            <group position={[0, 60.22, -5.92]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object002_Material009_0.geometry} material={materials['Material.009']} />
            </group>
            <group position={[0, 41.23, 198.28]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object003_Material010_0.geometry} material={materials['Material.010']} />
            </group>
            <group position={[0, 51.93, 187.38]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object004_Light_0.geometry} material={materials.Light} />
            </group>
            <group position={[0, 50.31, -98.18]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object005_Material008_0.geometry} material={materials['Material.008']} />
            </group>
            <group position={[0, 49.85, 206.28]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object006_LED_0.geometry} material={materials.material_13} />
            </group>
            <group position={[0, 69.91, -15.06]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object007_BRED_0.geometry} material={materials.BRED} />
            </group>
            <group position={[0, 80.89, -209.73]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object008_Shiny_Black_0.geometry} material={materials.Shiny_Black} />
            </group>
            <group position={[0, 68.01, -217.41]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object009_RED_0.geometry} material={materials.material_16} />
            </group>
            <group position={[0, 52.3, 193.75]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object011_xenon_0.geometry} material={materials.xenon} />
            </group>
            <group position={[0, 52.28, 192.84]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object012_Material012_0.geometry} material={materials['Material.012']} />
            </group>
            <group position={[0, 60, -3.13]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object013_Material017_0.geometry} material={materials['Material.017']} />
            </group>
            <group position={[0, 30.27, 5.07]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object014_Black_0.geometry} material={materials.Black} />
            </group>
            <group position={[0, 55.67, -0.62]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object015_Material016_0.geometry} material={materials['Material.016']} />
            </group>
            <group position={[0.06, 63.53, -44.83]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object016_Material013_0.geometry} material={materials['Material.013']} />
            </group>
            <group position={[0, 66.34, -9.37]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object017_Glass_0.geometry} material={materials.Glass} />
            </group>
            <group position={[0.06, 85.16, 30.97]} rotation={[0, 0, 0]} scale={[100, 100, 100]}>
              <mesh geometry={nodes.object018_Material018_0.geometry} material={materials['Material.018']} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
